# Generated by Django 4.1 on 2022-08-07 23:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Assocapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameassociation', models.CharField(blank=True, max_length=30, unique=True)),
                ('emailassociation', models.EmailField(max_length=250, unique=True)),
                ('phoneassociation', models.CharField(blank=True, max_length=20, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('addressassociation', models.CharField(blank=True, max_length=300, null=True)),
                ('cityassociation', models.CharField(blank=True, max_length=30, null=True)),
                ('Objectivesassociation', models.TextField(blank=True, null=True)),
                ('informationsassociation', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_association', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameorganisation', models.CharField(blank=True, max_length=30, unique=True)),
                ('emailorganisation', models.EmailField(max_length=250, unique=True)),
                ('phoneorganisation', models.CharField(blank=True, max_length=20, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('addressorganisation', models.CharField(blank=True, max_length=300, null=True)),
                ('cityorganisation', models.CharField(blank=True, max_length=30, null=True)),
                ('Objectivesorganisation', models.TextField(blank=True, null=True)),
                ('informationsorganisation', models.TextField(blank=True, null=True)),
                ('president_of_organisation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='president_organisation', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Memberassociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_member_association', models.CharField(blank=True, max_length=100, null=True)),
                ('association', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='name_association', to='Assocapi.association')),
                ('member_association', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member_association', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
