# Generated by Django 4.1 on 2022-08-08 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assocapi', '0003_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='emailassociation',
            field=models.EmailField(blank=True, max_length=250, unique=True),
        ),
    ]
