# Generated by Django 4.1 on 2022-08-08 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assocapi', '0004_alter_association_emailassociation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='emailassociation',
            field=models.EmailField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
