# Generated by Django 4.1 on 2022-08-08 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assocapi', '0005_alter_association_emailassociation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='nameassociation',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
