# Generated by Django 4.1 on 2022-08-08 23:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Assocapi', '0006_alter_association_nameassociation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_association', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='memberassociation',
            name='member_association',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_association', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='organization',
            name='president_of_organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='president_organisation', to=settings.AUTH_USER_MODEL),
        ),
    ]
