# Generated by Django 4.1 on 2022-08-12 12:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Assocapi', '0008_alter_association_options_association_date_added_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='organization',
            name='logoorganisation',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
