# Generated by Django 4.1 on 2022-08-12 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Assocapi', '0009_organization_date_added_organization_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberassociation',
            name='association',
        ),
        migrations.AddField(
            model_name='memberassociation',
            name='association',
            field=models.ManyToManyField(related_name='name_association', to='Assocapi.association'),
        ),
    ]
